### PR TITLE
Keep track of panel state, don't always call "showPanel"

### PR DESCRIPTION
**Pull request by bentoncase**
@Osmose r?

### CODE REVIEW

**Comment by Osmose** [comment]
The issue number in the commit message is wrong.

**Comment by Osmose** [comment]
Assuming you meant #66, this is an okay solution, but there's something you can use that is better; panel events.

The panel docs mention [events](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/panel#Events) that you can subscribe to using the [on method](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/panel#on%28type_listener%29). Instead of adding more state to track whether the panel has been shown or not, you should instead remove the tracking of panel shows from the button click handler, and instead register a listener for when the panel is shown and log to telemetry there. Then you have less state to track and can be confident that panel shows are logged in _all_ situations.

What do you think?

**Comment by bentoncase** [comment]
I agree that this is a better solution. It felt risky to have to keep track of state that the sdk/panel was certainly also storing. I'm doing a variation of this already for hide events. In the panel constructor method, one of the properties of the object passed to the constructor specifies my method to call on panel hide events. I'll use this technique for the show event too for symmetry.

**Comment by bentoncase** [comment]
@Osmose I'm using the sdk/panel's event listener for panel open events now. r?

**Comment by Osmose** [comment]
Much better. This looks great, just rebase the two commits into a single commit please, and I'm r+ on this. Nice work!

**Pull request merged**
