### PR TITLE
Specify addon is multiprocess compatible

### PR DESCRIPTION
**Pull request by bentoncase**
@mythmon r?

### CODE REVIEW

**Comment by mythmon** [comment]
Is this because the addon doesn't work at all on multiprocess? Or is this because multiprocess users will all be without addons right now, so we don't want to recommend them addons?

**Comment by bentoncase** [comment]
This addon won't work with multiprocess because it uses low level SDK APIs. The automatic validator on AMO is mad at me for not specifying this.

**Comment by bentoncase** [comment]
Screenshot from the addon listing on AMO

screen shot 2016-08-17 at 8 40 03 am

This will change "unknown" to something like "not compatible"

**Comment by mythmon** [comment]
Low level SDK APIs can be multiprocess safe. I'm not sure the addon is multiprocess compatible, but I'm pretty sure it is. Given the recent push to get multiprocess out on release, I think marking this addon as incompatible will drastically reduce our population. Can we work around this?

**Comment by mythmon** [comment]
r+

**Pull request merged**
